package org.mskcc.cmo.metadb;

import org.mskcc.cmo.metadb.util.ConsistencyCheckerUtil;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication(scanBasePackages = {"org.mskcc.cmo.common.*"})
public class ConsistencyCheckerApp implements CommandLineRunner{
    
    private ConsistencyCheckerUtil util = new ConsistencyCheckerUtil();
    
    private final String referenceJson = "{\n"
            + "  \"requestId\": \"08944_B\",\n"
            + "  \"recipe\": \"IMPACT468\",\n"
            + "  \"projectManagerName\": \"Ling, Lilan\",\n"
            + "  \"piEmail\": \"rudinc@mskcc.org\",\n"
            + "  \"labHeadName\": \"Charles Rudin\",\n"
            + "  \"labHeadEmail\": \"rudinc@mskcc.org\",\n"
            + "  \"investigatorName\": \"Viola Allaj\",\n"
            + "  \"investigatorEmail\": \"allajv@mskcc.org\",\n"
            + "  \"dataAnalystName\": \"John Poirier\",\n"
            + "  \"dataAnalystEmail\": \"poirierj@mskcc.org\",\n"
            + "  \"otherContactEmails\": \"poirierj@mskcc.org\",\n"
            + "  \"dataAccessEmails\": \"\",\n"
            + "  \"qcAccessEmails\": \"\",\n"
            + "  \"strand\": null,\n"
            + "  \"libraryType\": null,\n"
            + "  \"bicAnalysis\": true,\n"
            + "  \"samples\": [\n"
            + "    {\n"
            + "      \"igoId\": \"08944_B_1\",\n"
            + "      \"cmoSampleName\": \"C-MP76JR-X001-d\",\n"
            + "      \"sampleName\": \"LTG002_P3_17096_L1\",\n"
            + "      \"cmoSampleClass\": \"Primary\",\n"
            + "      \"cmoPatientId\": \"C-MP76JR\",\n"
            + "      \"investigatorSampleId\": \"LTG002_P3_17096_L1\",\n"
            + "      \"oncoTreeCode\": \"SCLC\",\n"
            + "      \"tumorOrNormal\": \"Tumor\",\n"
            + "      \"tissueLocation\": \"\",\n"
            + "      \"specimenType\": \"PDX\",\n"
            + "      \"sampleOrigin\": \"Tissue\",\n"
            + "      \"preservation\": \"Frozen\",\n"
            + "      \"collectionYear\": \"\",\n"
            + "      \"sex\": \"F\",\n"
            + "      \"species\": \"Human\",\n"
            + "      \"tubeId\": \"\",\n"
            + "      \"cfDNA2dBarcode\": null,\n"
            + "      \"baitSet\": \"IMPACT468_BAITS\",\n"
            + "      \"qcReports\": [],\n"
            + "      \"libraries\": [\n"
            + "        {\n"
            + "          \"barcodeId\": \"IDT29\",\n"
            + "          \"barcodeIndex\": \"ATTGAGGA\",\n"
            + "          \"libraryIgoId\": \"08944_B_1_1_1_1\",\n"
            + "          \"libraryVolume\": 35,\n"
            + "          \"libraryConcentrationNgul\": 34.8,\n"
            + "          \"dnaInputNg\": null,\n"
            + "          \"captureConcentrationNm\": \"11.49425287356322\",\n"
            + "          \"captureInputNg\": \"400.0\",\n"
            + "          \"captureName\": \"Pool-08944_B-Tube7_1\",\n"
            + "          \"runs\": [\n"
            + "            {\n"
            + "              \"runMode\": \"HiSeq High Output\",\n"
            + "              \"runId\": \"PITT_0319\",\n"
            + "              \"flowCellId\": \"H3MV7BBXY\",\n"
            + "              \"readLength\": \"\",\n"
            + "              \"runDate\": \"2019-02-11\",\n"
            + "              \"flowCellLanes\": [\n"
            + "                5\n"
            + "              ],\n"
            + "              \"fastqs\": [\n"
            + "                \"/igo/delivery/FASTQ/PITT_0319_BH3MV7BBXY/Project_08944_B/Sample_LTG002_P3_17096_L1_IGO_08944_B_1/LTG002_P3_17096_L1_IGO_08944_B_1_S82_R1_001.fastq.gz\",\n"
            + "                \"/igo/delivery/FASTQ/PITT_0319_BH3MV7BBXY/Project_08944_B/Sample_LTG002_P3_17096_L1_IGO_08944_B_1/LTG002_P3_17096_L1_IGO_08944_B_1_S82_R2_001.fastq.gz\"\n"
            + "              ]\n"
            + "            }\n"
            + "          ]\n"
            + "        }\n"
            + "      ]\n"
            + "    },\n"
            + "    {\n"
            + "      \"igoId\": \"08944_B_2\",\n"
            + "      \"cmoSampleName\": \"C-MP76JR-N001-d\",\n"
            + "      \"sampleName\": \"17-0001535a\",\n"
            + "      \"cmoSampleClass\": \"Normal\",\n"
            + "      \"cmoPatientId\": \"C-MP76JR\",\n"
            + "      \"investigatorSampleId\": \"17-0001535a\",\n"
            + "      \"oncoTreeCode\": null,\n"
            + "      \"tumorOrNormal\": \"Normal\",\n"
            + "      \"tissueLocation\": \"\",\n"
            + "      \"specimenType\": \"Blood\",\n"
            + "      \"sampleOrigin\": \"Whole Blood\",\n"
            + "      \"preservation\": \"Frozen\",\n"
            + "      \"collectionYear\": \"\",\n"
            + "      \"sex\": \"F\",\n"
            + "      \"species\": \"Human\",\n"
            + "      \"tubeId\": \"\",\n"
            + "      \"cfDNA2dBarcode\": null,\n"
            + "      \"baitSet\": \"IMPACT468_BAITS\",\n"
            + "      \"qcReports\": [],\n"
            + "      \"libraries\": [\n"
            + "        {\n"
            + "          \"barcodeId\": \"IDT41\",\n"
            + "          \"barcodeIndex\": \"CGACTGGA\",\n"
            + "          \"libraryIgoId\": \"08944_B_2_1_1_1\",\n"
            + "          \"libraryVolume\": 35,\n"
            + "          \"libraryConcentrationNgul\": 33.5,\n"
            + "          \"dnaInputNg\": null,\n"
            + "          \"captureConcentrationNm\": \"5.074626865671642\",\n"
            + "          \"captureInputNg\": \"170.0\",\n"
            + "          \"captureName\": \"Pool-08944_B-Tube7_1\",\n"
            + "          \"runs\": [\n"
            + "            {\n"
            + "              \"runMode\": \"HiSeq High Output\",\n"
            + "              \"runId\": \"PITT_0319\",\n"
            + "              \"flowCellId\": \"H3MV7BBXY\",\n"
            + "              \"readLength\": \"\",\n"
            + "              \"runDate\": \"2019-02-11\",\n"
            + "              \"flowCellLanes\": [\n"
            + "                5\n"
            + "              ],\n"
            + "              \"fastqs\": [\n"
            + "                \"/igo/delivery/FASTQ/PITT_0319_BH3MV7BBXY/Project_08944_B/Sample_17-0001535a_IGO_08944_B_2/17-0001535a_IGO_08944_B_2_S83_R2_001.fastq.gz\",\n"
            + "                \"/igo/delivery/FASTQ/PITT_0319_BH3MV7BBXY/Project_08944_B/Sample_17-0001535a_IGO_08944_B_2/17-0001535a_IGO_08944_B_2_S83_R1_001.fastq.gz\"\n"
            + "              ]\n"
            + "            }\n"
            + "          ]\n"
            + "        }\n"
            + "      ]\n"
            + "    },\n"
            + "    {\n"
            + "      \"igoId\": \"08944_B_3\",\n"
            + "      \"cmoSampleName\": \"C-4LM16H-X001-d\",\n"
            + "      \"sampleName\": \"LTG017_P1_17095a_R_43\",\n"
            + "      \"cmoSampleClass\": \"Primary\",\n"
            + "      \"cmoPatientId\": \"C-4LM16H\",\n"
            + "      \"investigatorSampleId\": \"LTG017_P1_17095a_R_43\",\n"
            + "      \"oncoTreeCode\": \"SCLC\",\n"
            + "      \"tumorOrNormal\": \"Tumor\",\n"
            + "      \"tissueLocation\": \"\",\n"
            + "      \"specimenType\": \"PDX\",\n"
            + "      \"sampleOrigin\": \"Tissue\",\n"
            + "      \"preservation\": \"Frozen\",\n"
            + "      \"collectionYear\": \"\",\n"
            + "      \"sex\": \"M\",\n"
            + "      \"species\": \"Human\",\n"
            + "      \"tubeId\": \"\",\n"
            + "      \"cfDNA2dBarcode\": null,\n"
            + "      \"baitSet\": \"IMPACT468_BAITS\",\n"
            + "      \"qcReports\": [],\n"
            + "      \"libraries\": [\n"
            + "        {\n"
            + "          \"barcodeId\": \"IDT53\",\n"
            + "          \"barcodeIndex\": \"GCTCGGTA\",\n"
            + "          \"libraryIgoId\": \"08944_B_3_1_1_1\",\n"
            + "          \"libraryVolume\": 35,\n"
            + "          \"libraryConcentrationNgul\": 35.2,\n"
            + "          \"dnaInputNg\": null,\n"
            + "          \"captureConcentrationNm\": \"11.363636363636363\",\n"
            + "          \"captureInputNg\": \"400.0\",\n"
            + "          \"captureName\": \"Pool-08944_B-Tube7_1\",\n"
            + "          \"runs\": [\n"
            + "            {\n"
            + "              \"runMode\": \"HiSeq High Output\",\n"
            + "              \"runId\": \"PITT_0319\",\n"
            + "              \"flowCellId\": \"H3MV7BBXY\",\n"
            + "              \"readLength\": \"\",\n"
            + "              \"runDate\": \"2019-02-11\",\n"
            + "              \"flowCellLanes\": [\n"
            + "                5\n"
            + "              ],\n"
            + "              \"fastqs\": [\n"
            + "                \"/igo/delivery/FASTQ/PITT_0319_BH3MV7BBXY/Project_08944_B/Sample_LTG017_P1_17095a_R_43_IGO_08944_B_3/LTG017_P1_17095a_R_43_IGO_08944_B_3_S84_R1_001.fastq.gz\",\n"
            + "                \"/igo/delivery/FASTQ/PITT_0319_BH3MV7BBXY/Project_08944_B/Sample_LTG017_P1_17095a_R_43_IGO_08944_B_3/LTG017_P1_17095a_R_43_IGO_08944_B_3_S84_R2_001.fastq.gz\"\n"
            + "              ]\n"
            + "            }\n"
            + "          ]\n"
            + "        }\n"
            + "      ]\n"
            + "    },\n"
            + "    {\n"
            + "      \"igoId\": \"08944_B_4\",\n"
            + "      \"cmoSampleName\": \"C-4LM16H-N001-d\",\n"
            + "      \"sampleName\": \"17-0010557a\",\n"
            + "      \"cmoSampleClass\": \"Normal\",\n"
            + "      \"cmoPatientId\": \"C-4LM16H\",\n"
            + "      \"investigatorSampleId\": \"17-0010557a\",\n"
            + "      \"oncoTreeCode\": null,\n"
            + "      \"tumorOrNormal\": \"Normal\",\n"
            + "      \"tissueLocation\": \"\",\n"
            + "      \"specimenType\": \"Blood\",\n"
            + "      \"sampleOrigin\": \"Whole Blood\",\n"
            + "      \"preservation\": \"Frozen\",\n"
            + "      \"collectionYear\": \"\",\n"
            + "      \"sex\": \"M\",\n"
            + "      \"species\": \"Human\",\n"
            + "      \"tubeId\": \"\",\n"
            + "      \"cfDNA2dBarcode\": null,\n"
            + "      \"baitSet\": \"IMPACT468_BAITS\",\n"
            + "      \"qcReports\": [],\n"
            + "      \"libraries\": [\n"
            + "        {\n"
            + "          \"barcodeId\": \"IDT65\",\n"
            + "          \"barcodeIndex\": \"TGGAACAA\",\n"
            + "          \"libraryIgoId\": \"08944_B_4_1_1_1\",\n"
            + "          \"libraryVolume\": 35,\n"
            + "          \"libraryConcentrationNgul\": 34.1,\n"
            + "          \"dnaInputNg\": null,\n"
            + "          \"captureConcentrationNm\": \"4.9853372434017595\",\n"
            + "          \"captureInputNg\": \"170.0\",\n"
            + "          \"captureName\": \"Pool-08944_B-Tube7_1\",\n"
            + "          \"runs\": [\n"
            + "            {\n"
            + "              \"runMode\": \"HiSeq High Output\",\n"
            + "              \"runId\": \"PITT_0319\",\n"
            + "              \"flowCellId\": \"H3MV7BBXY\",\n"
            + "              \"readLength\": \"\",\n"
            + "              \"runDate\": \"2019-02-11\",\n"
            + "              \"flowCellLanes\": [\n"
            + "                5\n"
            + "              ],\n"
            + "              \"fastqs\": [\n"
            + "                \"/igo/delivery/FASTQ/PITT_0319_BH3MV7BBXY/Project_08944_B/Sample_17-0010557a_IGO_08944_B_4/17-0010557a_IGO_08944_B_4_S85_R1_001.fastq.gz\",\n"
            + "                \"/igo/delivery/FASTQ/PITT_0319_BH3MV7BBXY/Project_08944_B/Sample_17-0010557a_IGO_08944_B_4/17-0010557a_IGO_08944_B_4_S85_R2_001.fastq.gz\"\n"
            + "              ]\n"
            + "            }\n"
            + "          ]\n"
            + "        }\n"
            + "      ]\n"
            + "    }\n"
            + "  ],\n"
            + "  \"pooledNormals\": [\n"
            + "    \"/igo/delivery/FASTQ/PITT_0319_BH3MV7BBXY/Project_POOLEDNORMALS/Sample_FFPEPOOLEDNORMAL_IGO_IMPACT468_GATGAATC/FFPEPOOLEDNORMAL_IGO_IMPACT468_GATGAATC_S23_R1_001.fastq.gz\",\n"
            + "    \"/igo/delivery/FASTQ/PITT_0319_BH3MV7BBXY/Project_POOLEDNORMALS/Sample_FFPEPOOLEDNORMAL_IGO_IMPACT468_GATGAATC/FFPEPOOLEDNORMAL_IGO_IMPACT468_GATGAATC_S23_R2_001.fastq.gz\",\n"
            + "    \"/igo/delivery/FASTQ/PITT_0319_BH3MV7BBXY/Project_POOLEDNORMALS/Sample_FROZENPOOLEDNORMAL_IGO_AMBIGUOUS_GCCAAGAC/FROZENPOOLEDNORMAL_IGO_AMBIGUOUS_GCCAAGAC_S86_R1_001.fastq.gz\",\n"
            + "    \"/igo/delivery/FASTQ/PITT_0319_BH3MV7BBXY/Project_POOLEDNORMALS/Sample_FROZENPOOLEDNORMAL_IGO_AMBIGUOUS_GCCAAGAC/FROZENPOOLEDNORMAL_IGO_AMBIGUOUS_GCCAAGAC_S86_R2_001.fastq.gz\",\n"
            + "    \"/igo/delivery/FASTQ/PITT_0319_BH3MV7BBXY/Project_POOLEDNORMALS/Sample_FROZENPOOLEDNORMAL_IGO_HemePACT_v4_GCCAAGAC/FROZENPOOLEDNORMAL_IGO_HemePACT_v4_GCCAAGAC_S147_R1_001.fastq.gz\",\n"
            + "    \"/igo/delivery/FASTQ/PITT_0319_BH3MV7BBXY/Project_POOLEDNORMALS/Sample_FROZENPOOLEDNORMAL_IGO_HemePACT_v4_GCCAAGAC/FROZENPOOLEDNORMAL_IGO_HemePACT_v4_GCCAAGAC_S147_R2_001.fastq.gz\",\n"
            + "    \"/igo/delivery/FASTQ/PITT_0319_BH3MV7BBXY/Project_POOLEDNORMALS/Sample_FROZENPOOLEDNORMAL_IGO_IMPACT468_GCCAAGAC/FROZENPOOLEDNORMAL_IGO_IMPACT468_GCCAAGAC_S196_R1_001.fastq.gz\",\n"
            + "    \"/igo/delivery/FASTQ/PITT_0319_BH3MV7BBXY/Project_POOLEDNORMALS/Sample_FROZENPOOLEDNORMAL_IGO_IMPACT468_GCCAAGAC/FROZENPOOLEDNORMAL_IGO_IMPACT468_GCCAAGAC_S196_R2_001.fastq.gz\",\n"
            + "    \"/igo/delivery/FASTQ/PITT_0319_BH3MV7BBXY/Project_POOLEDNORMALS/Sample_MOUSEPOOLEDNORMAL_IGO_AMBIGUOUS_AATCCGTC/MOUSEPOOLEDNORMAL_IGO_AMBIGUOUS_AATCCGTC_S61_R1_001.fastq.gz\",\n"
            + "    \"/igo/delivery/FASTQ/PITT_0319_BH3MV7BBXY/Project_POOLEDNORMALS/Sample_MOUSEPOOLEDNORMAL_IGO_AMBIGUOUS_AATCCGTC/MOUSEPOOLEDNORMAL_IGO_AMBIGUOUS_AATCCGTC_S61_R2_001.fastq.gz\"\n"
            + "  ],\n"
            + "  \"cmoRequest\": true,\n"
            + "  \"projectId\": \"08944\"\n"
            + "}";
    private final String targetJson = "{\n"
            + "  \"metaDbRequestId\": \"95695fac-a1bb-4b51-b022-fed67e779429\",\n"
            + "  \"projectId\": \"08944\",\n"
            + "  \"requestId\": \"08944_B\",\n"
            + "  \"recipe\": \"IMPACT468\",\n"
            + "  \"projectManagerName\": \"Ling, Lilan\",\n"
            + "  \"piEmail\": \"rudinc@mskcc.org\",\n"
            + "  \"labHeadName\": \"Charles Rudin\",\n"
            + "  \"labHeadEmail\": \"rudinc@mskcc.org\",\n"
            + "  \"investigatorName\": \"Viola Allaj\",\n"
            + "  \"investigatorEmail\": \"allajv@mskcc.org\",\n"
            + "  \"dataAnalystName\": \"John Poirier\",\n"
            + "  \"dataAnalystEmail\": \"poirierj@mskcc.org\",\n"
            + "  \"otherContactEmails\": \"poirierj@mskcc.org\",\n"
            + "  \"dataAccessEmails\": \"\",\n"
            + "  \"qcAccessEmails\": \"\",\n"
            + "  \"strand\": null,\n"
            + "  \"libraryType\": null,\n"
            + "  \"cmoRequest\": true,\n"
            + "  \"bicAnalysis\": true,\n"
            + "  \"requestJson\": \"{\\\"requestId\\\":\\\"08944_B\\\",\\\"recipe\\\":\\\"IMPACT468\\\",\\\"projectManagerName\\\":\\\"Ling, Lilan\\\",\\\"piEmail\\\":\\\"rudinc@mskcc.org\\\",\\\"labHeadName\\\":\\\"Charles Rudin\\\",\\\"labHeadEmail\\\":\\\"rudinc@mskcc.org\\\",\\\"investigatorName\\\":\\\"Viola Allaj\\\",\\\"investigatorEmail\\\":\\\"allajv@mskcc.org\\\",\\\"dataAnalystName\\\":\\\"John Poirier\\\",\\\"dataAnalystEmail\\\":\\\"poirierj@mskcc.org\\\",\\\"otherContactEmails\\\":\\\"poirierj@mskcc.org\\\",\\\"dataAccessEmails\\\":\\\"\\\",\\\"qcAccessEmails\\\":\\\"\\\",\\\"strand\\\":null,\\\"libraryType\\\":null,\\\"bicAnalysis\\\":true,\\\"samples\\\":[{\\\"igoId\\\":\\\"08944_B_1\\\",\\\"cmoSampleName\\\":\\\"C-MP76JR-X001-d\\\",\\\"sampleName\\\":\\\"LTG002_P3_17096_L1\\\",\\\"cmoSampleClass\\\":\\\"Primary\\\",\\\"cmoPatientId\\\":\\\"C-MP76JR\\\",\\\"investigatorSampleId\\\":\\\"LTG002_P3_17096_L1\\\",\\\"oncoTreeCode\\\":\\\"SCLC\\\",\\\"tumorOrNormal\\\":\\\"Tumor\\\",\\\"tissueLocation\\\":\\\"\\\",\\\"specimenType\\\":\\\"PDX\\\",\\\"sampleOrigin\\\":\\\"Tissue\\\",\\\"preservation\\\":\\\"Frozen\\\",\\\"collectionYear\\\":\\\"\\\",\\\"sex\\\":\\\"F\\\",\\\"species\\\":\\\"Human\\\",\\\"tubeId\\\":\\\"\\\",\\\"cfDNA2dBarcode\\\":null,\\\"baitSet\\\":\\\"IMPACT468_BAITS\\\",\\\"qcReports\\\":[],\\\"libraries\\\":[{\\\"barcodeId\\\":\\\"IDT29\\\",\\\"barcodeIndex\\\":\\\"ATTGAGGA\\\",\\\"libraryIgoId\\\":\\\"08944_B_1_1_1_1\\\",\\\"libraryVolume\\\":35.0,\\\"libraryConcentrationNgul\\\":34.8,\\\"dnaInputNg\\\":null,\\\"captureConcentrationNm\\\":\\\"11.49425287356322\\\",\\\"captureInputNg\\\":\\\"400.0\\\",\\\"captureName\\\":\\\"Pool-08944_B-Tube7_1\\\",\\\"runs\\\":[{\\\"runMode\\\":\\\"HiSeq High Output\\\",\\\"runId\\\":\\\"PITT_0319\\\",\\\"flowCellId\\\":\\\"H3MV7BBXY\\\",\\\"readLength\\\":\\\"\\\",\\\"runDate\\\":\\\"2019-02-11\\\",\\\"flowCellLanes\\\":[5],\\\"fastqs\\\":[\\\"/igo/delivery/FASTQ/PITT_0319_BH3MV7BBXY/Project_08944_B/Sample_LTG002_P3_17096_L1_IGO_08944_B_1/LTG002_P3_17096_L1_IGO_08944_B_1_S82_R1_001.fastq.gz\\\",\\\"/igo/delivery/FASTQ/PITT_0319_BH3MV7BBXY/Project_08944_B/Sample_LTG002_P3_17096_L1_IGO_08944_B_1/LTG002_P3_17096_L1_IGO_08944_B_1_S82_R2_001.fastq.gz\\\"]}]}]},{\\\"igoId\\\":\\\"08944_B_2\\\",\\\"cmoSampleName\\\":\\\"C-MP76JR-N001-d\\\",\\\"sampleName\\\":\\\"17-0001535a\\\",\\\"cmoSampleClass\\\":\\\"Normal\\\",\\\"cmoPatientId\\\":\\\"C-MP76JR\\\",\\\"investigatorSampleId\\\":\\\"17-0001535a\\\",\\\"oncoTreeCode\\\":null,\\\"tumorOrNormal\\\":\\\"Normal\\\",\\\"tissueLocation\\\":\\\"\\\",\\\"specimenType\\\":\\\"Blood\\\",\\\"sampleOrigin\\\":\\\"Whole Blood\\\",\\\"preservation\\\":\\\"Frozen\\\",\\\"collectionYear\\\":\\\"\\\",\\\"sex\\\":\\\"F\\\",\\\"species\\\":\\\"Human\\\",\\\"tubeId\\\":\\\"\\\",\\\"cfDNA2dBarcode\\\":null,\\\"baitSet\\\":\\\"IMPACT468_BAITS\\\",\\\"qcReports\\\":[],\\\"libraries\\\":[{\\\"barcodeId\\\":\\\"IDT41\\\",\\\"barcodeIndex\\\":\\\"CGACTGGA\\\",\\\"libraryIgoId\\\":\\\"08944_B_2_1_1_1\\\",\\\"libraryVolume\\\":35.0,\\\"libraryConcentrationNgul\\\":33.5,\\\"dnaInputNg\\\":null,\\\"captureConcentrationNm\\\":\\\"5.074626865671642\\\",\\\"captureInputNg\\\":\\\"170.0\\\",\\\"captureName\\\":\\\"Pool-08944_B-Tube7_1\\\",\\\"runs\\\":[{\\\"runMode\\\":\\\"HiSeq High Output\\\",\\\"runId\\\":\\\"PITT_0319\\\",\\\"flowCellId\\\":\\\"H3MV7BBXY\\\",\\\"readLength\\\":\\\"\\\",\\\"runDate\\\":\\\"2019-02-11\\\",\\\"flowCellLanes\\\":[5],\\\"fastqs\\\":[\\\"/igo/delivery/FASTQ/PITT_0319_BH3MV7BBXY/Project_08944_B/Sample_17-0001535a_IGO_08944_B_2/17-0001535a_IGO_08944_B_2_S83_R2_001.fastq.gz\\\",\\\"/igo/delivery/FASTQ/PITT_0319_BH3MV7BBXY/Project_08944_B/Sample_17-0001535a_IGO_08944_B_2/17-0001535a_IGO_08944_B_2_S83_R1_001.fastq.gz\\\"]}]}]},{\\\"igoId\\\":\\\"08944_B_3\\\",\\\"cmoSampleName\\\":\\\"C-4LM16H-X001-d\\\",\\\"sampleName\\\":\\\"LTG017_P1_17095a_R_43\\\",\\\"cmoSampleClass\\\":\\\"Primary\\\",\\\"cmoPatientId\\\":\\\"C-4LM16H\\\",\\\"investigatorSampleId\\\":\\\"LTG017_P1_17095a_R_43\\\",\\\"oncoTreeCode\\\":\\\"SCLC\\\",\\\"tumorOrNormal\\\":\\\"Tumor\\\",\\\"tissueLocation\\\":\\\"\\\",\\\"specimenType\\\":\\\"PDX\\\",\\\"sampleOrigin\\\":\\\"Tissue\\\",\\\"preservation\\\":\\\"Frozen\\\",\\\"collectionYear\\\":\\\"\\\",\\\"sex\\\":\\\"M\\\",\\\"species\\\":\\\"Human\\\",\\\"tubeId\\\":\\\"\\\",\\\"cfDNA2dBarcode\\\":null,\\\"baitSet\\\":\\\"IMPACT468_BAITS\\\",\\\"qcReports\\\":[],\\\"libraries\\\":[{\\\"barcodeId\\\":\\\"IDT53\\\",\\\"barcodeIndex\\\":\\\"GCTCGGTA\\\",\\\"libraryIgoId\\\":\\\"08944_B_3_1_1_1\\\",\\\"libraryVolume\\\":35.0,\\\"libraryConcentrationNgul\\\":35.2,\\\"dnaInputNg\\\":null,\\\"captureConcentrationNm\\\":\\\"11.363636363636363\\\",\\\"captureInputNg\\\":\\\"400.0\\\",\\\"captureName\\\":\\\"Pool-08944_B-Tube7_1\\\",\\\"runs\\\":[{\\\"runMode\\\":\\\"HiSeq High Output\\\",\\\"runId\\\":\\\"PITT_0319\\\",\\\"flowCellId\\\":\\\"H3MV7BBXY\\\",\\\"readLength\\\":\\\"\\\",\\\"runDate\\\":\\\"2019-02-11\\\",\\\"flowCellLanes\\\":[5],\\\"fastqs\\\":[\\\"/igo/delivery/FASTQ/PITT_0319_BH3MV7BBXY/Project_08944_B/Sample_LTG017_P1_17095a_R_43_IGO_08944_B_3/LTG017_P1_17095a_R_43_IGO_08944_B_3_S84_R1_001.fastq.gz\\\",\\\"/igo/delivery/FASTQ/PITT_0319_BH3MV7BBXY/Project_08944_B/Sample_LTG017_P1_17095a_R_43_IGO_08944_B_3/LTG017_P1_17095a_R_43_IGO_08944_B_3_S84_R2_001.fastq.gz\\\"]}]}]},{\\\"igoId\\\":\\\"08944_B_4\\\",\\\"cmoSampleName\\\":\\\"C-4LM16H-N001-d\\\",\\\"sampleName\\\":\\\"17-0010557a\\\",\\\"cmoSampleClass\\\":\\\"Normal\\\",\\\"cmoPatientId\\\":\\\"C-4LM16H\\\",\\\"investigatorSampleId\\\":\\\"17-0010557a\\\",\\\"oncoTreeCode\\\":null,\\\"tumorOrNormal\\\":\\\"Normal\\\",\\\"tissueLocation\\\":\\\"\\\",\\\"specimenType\\\":\\\"Blood\\\",\\\"sampleOrigin\\\":\\\"Whole Blood\\\",\\\"preservation\\\":\\\"Frozen\\\",\\\"collectionYear\\\":\\\"\\\",\\\"sex\\\":\\\"M\\\",\\\"species\\\":\\\"Human\\\",\\\"tubeId\\\":\\\"\\\",\\\"cfDNA2dBarcode\\\":null,\\\"baitSet\\\":\\\"IMPACT468_BAITS\\\",\\\"qcReports\\\":[],\\\"libraries\\\":[{\\\"barcodeId\\\":\\\"IDT65\\\",\\\"barcodeIndex\\\":\\\"TGGAACAA\\\",\\\"libraryIgoId\\\":\\\"08944_B_4_1_1_1\\\",\\\"libraryVolume\\\":35.0,\\\"libraryConcentrationNgul\\\":34.1,\\\"dnaInputNg\\\":null,\\\"captureConcentrationNm\\\":\\\"4.9853372434017595\\\",\\\"captureInputNg\\\":\\\"170.0\\\",\\\"captureName\\\":\\\"Pool-08944_B-Tube7_1\\\",\\\"runs\\\":[{\\\"runMode\\\":\\\"HiSeq High Output\\\",\\\"runId\\\":\\\"PITT_0319\\\",\\\"flowCellId\\\":\\\"H3MV7BBXY\\\",\\\"readLength\\\":\\\"\\\",\\\"runDate\\\":\\\"2019-02-11\\\",\\\"flowCellLanes\\\":[5],\\\"fastqs\\\":[\\\"/igo/delivery/FASTQ/PITT_0319_BH3MV7BBXY/Project_08944_B/Sample_17-0010557a_IGO_08944_B_4/17-0010557a_IGO_08944_B_4_S85_R1_001.fastq.gz\\\",\\\"/igo/delivery/FASTQ/PITT_0319_BH3MV7BBXY/Project_08944_B/Sample_17-0010557a_IGO_08944_B_4/17-0010557a_IGO_08944_B_4_S85_R2_001.fastq.gz\\\"]}]}]}],\\\"pooledNormals\\\":[\\\"/igo/delivery/FASTQ/PITT_0319_BH3MV7BBXY/Project_POOLEDNORMALS/Sample_FFPEPOOLEDNORMAL_IGO_IMPACT468_GATGAATC/FFPEPOOLEDNORMAL_IGO_IMPACT468_GATGAATC_S23_R1_001.fastq.gz\\\",\\\"/igo/delivery/FASTQ/PITT_0319_BH3MV7BBXY/Project_POOLEDNORMALS/Sample_FFPEPOOLEDNORMAL_IGO_IMPACT468_GATGAATC/FFPEPOOLEDNORMAL_IGO_IMPACT468_GATGAATC_S23_R2_001.fastq.gz\\\",\\\"/igo/delivery/FASTQ/PITT_0319_BH3MV7BBXY/Project_POOLEDNORMALS/Sample_FROZENPOOLEDNORMAL_IGO_AMBIGUOUS_GCCAAGAC/FROZENPOOLEDNORMAL_IGO_AMBIGUOUS_GCCAAGAC_S86_R1_001.fastq.gz\\\",\\\"/igo/delivery/FASTQ/PITT_0319_BH3MV7BBXY/Project_POOLEDNORMALS/Sample_FROZENPOOLEDNORMAL_IGO_AMBIGUOUS_GCCAAGAC/FROZENPOOLEDNORMAL_IGO_AMBIGUOUS_GCCAAGAC_S86_R2_001.fastq.gz\\\",\\\"/igo/delivery/FASTQ/PITT_0319_BH3MV7BBXY/Project_POOLEDNORMALS/Sample_FROZENPOOLEDNORMAL_IGO_HemePACT_v4_GCCAAGAC/FROZENPOOLEDNORMAL_IGO_HemePACT_v4_GCCAAGAC_S147_R1_001.fastq.gz\\\",\\\"/igo/delivery/FASTQ/PITT_0319_BH3MV7BBXY/Project_POOLEDNORMALS/Sample_FROZENPOOLEDNORMAL_IGO_HemePACT_v4_GCCAAGAC/FROZENPOOLEDNORMAL_IGO_HemePACT_v4_GCCAAGAC_S147_R2_001.fastq.gz\\\",\\\"/igo/delivery/FASTQ/PITT_0319_BH3MV7BBXY/Project_POOLEDNORMALS/Sample_FROZENPOOLEDNORMAL_IGO_IMPACT468_GCCAAGAC/FROZENPOOLEDNORMAL_IGO_IMPACT468_GCCAAGAC_S196_R1_001.fastq.gz\\\",\\\"/igo/delivery/FASTQ/PITT_0319_BH3MV7BBXY/Project_POOLEDNORMALS/Sample_FROZENPOOLEDNORMAL_IGO_IMPACT468_GCCAAGAC/FROZENPOOLEDNORMAL_IGO_IMPACT468_GCCAAGAC_S196_R2_001.fastq.gz\\\",\\\"/igo/delivery/FASTQ/PITT_0319_BH3MV7BBXY/Project_POOLEDNORMALS/Sample_MOUSEPOOLEDNORMAL_IGO_AMBIGUOUS_AATCCGTC/MOUSEPOOLEDNORMAL_IGO_AMBIGUOUS_AATCCGTC_S61_R1_001.fastq.gz\\\",\\\"/igo/delivery/FASTQ/PITT_0319_BH3MV7BBXY/Project_POOLEDNORMALS/Sample_MOUSEPOOLEDNORMAL_IGO_AMBIGUOUS_AATCCGTC/MOUSEPOOLEDNORMAL_IGO_AMBIGUOUS_AATCCGTC_S61_R2_001.fastq.gz\\\"],\\\"cmoRequest\\\":true,\\\"projectId\\\":\\\"08944\\\"}\",\n"
            + "  \"pooledNormals\": [\n"
            + "    \"/igo/delivery/FASTQ/PITT_0319_BH3MV7BBXY/Project_POOLEDNORMALS/Sample_FFPEPOOLEDNORMAL_IGO_IMPACT468_GATGAATC/FFPEPOOLEDNORMAL_IGO_IMPACT468_GATGAATC_S23_R1_001.fastq.gz\",\n"
            + "    \"/igo/delivery/FASTQ/PITT_0319_BH3MV7BBXY/Project_POOLEDNORMALS/Sample_FFPEPOOLEDNORMAL_IGO_IMPACT468_GATGAATC/FFPEPOOLEDNORMAL_IGO_IMPACT468_GATGAATC_S23_R2_001.fastq.gz\",\n"
            + "    \"/igo/delivery/FASTQ/PITT_0319_BH3MV7BBXY/Project_POOLEDNORMALS/Sample_FROZENPOOLEDNORMAL_IGO_AMBIGUOUS_GCCAAGAC/FROZENPOOLEDNORMAL_IGO_AMBIGUOUS_GCCAAGAC_S86_R1_001.fastq.gz\",\n"
            + "    \"/igo/delivery/FASTQ/PITT_0319_BH3MV7BBXY/Project_POOLEDNORMALS/Sample_FROZENPOOLEDNORMAL_IGO_AMBIGUOUS_GCCAAGAC/FROZENPOOLEDNORMAL_IGO_AMBIGUOUS_GCCAAGAC_S86_R2_001.fastq.gz\",\n"
            + "    \"/igo/delivery/FASTQ/PITT_0319_BH3MV7BBXY/Project_POOLEDNORMALS/Sample_FROZENPOOLEDNORMAL_IGO_HemePACT_v4_GCCAAGAC/FROZENPOOLEDNORMAL_IGO_HemePACT_v4_GCCAAGAC_S147_R1_001.fastq.gz\",\n"
            + "    \"/igo/delivery/FASTQ/PITT_0319_BH3MV7BBXY/Project_POOLEDNORMALS/Sample_FROZENPOOLEDNORMAL_IGO_HemePACT_v4_GCCAAGAC/FROZENPOOLEDNORMAL_IGO_HemePACT_v4_GCCAAGAC_S147_R2_001.fastq.gz\",\n"
            + "    \"/igo/delivery/FASTQ/PITT_0319_BH3MV7BBXY/Project_POOLEDNORMALS/Sample_FROZENPOOLEDNORMAL_IGO_IMPACT468_GCCAAGAC/FROZENPOOLEDNORMAL_IGO_IMPACT468_GCCAAGAC_S196_R1_001.fastq.gz\",\n"
            + "    \"/igo/delivery/FASTQ/PITT_0319_BH3MV7BBXY/Project_POOLEDNORMALS/Sample_FROZENPOOLEDNORMAL_IGO_IMPACT468_GCCAAGAC/FROZENPOOLEDNORMAL_IGO_IMPACT468_GCCAAGAC_S196_R2_001.fastq.gz\",\n"
            + "    \"/igo/delivery/FASTQ/PITT_0319_BH3MV7BBXY/Project_POOLEDNORMALS/Sample_MOUSEPOOLEDNORMAL_IGO_AMBIGUOUS_AATCCGTC/MOUSEPOOLEDNORMAL_IGO_AMBIGUOUS_AATCCGTC_S61_R1_001.fastq.gz\",\n"
            + "    \"/igo/delivery/FASTQ/PITT_0319_BH3MV7BBXY/Project_POOLEDNORMALS/Sample_MOUSEPOOLEDNORMAL_IGO_AMBIGUOUS_AATCCGTC/MOUSEPOOLEDNORMAL_IGO_AMBIGUOUS_AATCCGTC_S61_R2_001.fastq.gz\"\n"
            + "  ],\n"
            + "  \"samples\": [\n"
            + "    {\n"
            + "      \"metaDbSampleId\": \"a5e135f2-02d3-4898-b84a-ff6bc9dc3283\",\n"
            + "      \"importDate\": \"2021-03-18\",\n"
            + "      \"cmoSampleName\": \"C-4LM16H-X001-d\",\n"
            + "      \"sampleName\": \"LTG017_P1_17095a_R_43\",\n"
            + "      \"cmoSampleClass\": \"Primary\",\n"
            + "      \"oncoTreeCode\": \"SCLC\",\n"
            + "      \"collectionYear\": \"\",\n"
            + "      \"tubeId\": \"\",\n"
            + "      \"qcReports\": [],\n"
            + "      \"libraries\": [\n"
            + "        {\n"
            + "          \"barcodeId\": \"IDT53\",\n"
            + "          \"barcodeIndex\": \"GCTCGGTA\",\n"
            + "          \"libraryIgoId\": \"08944_B_3_1_1_1\",\n"
            + "          \"libraryVolume\": 35,\n"
            + "          \"libraryConcentrationNgul\": 35.2,\n"
            + "          \"dnaInputNg\": null,\n"
            + "          \"captureConcentrationNm\": \"11.363636363636363\",\n"
            + "          \"captureInputNg\": \"400.0\",\n"
            + "          \"captureName\": \"Pool-08944_B-Tube7_1\",\n"
            + "          \"runs\": [\n"
            + "            {\n"
            + "              \"runMode\": \"HiSeq High Output\",\n"
            + "              \"runId\": \"PITT_0319\",\n"
            + "              \"flowCellId\": \"H3MV7BBXY\",\n"
            + "              \"readLength\": \"\",\n"
            + "              \"runDate\": \"2019-02-11\",\n"
            + "              \"flowCellLanes\": [\n"
            + "                5\n"
            + "              ],\n"
            + "              \"fastqs\": [\n"
            + "                \"/igo/delivery/FASTQ/PITT_0319_BH3MV7BBXY/Project_08944_B/Sample_LTG017_P1_17095a_R_43_IGO_08944_B_3/LTG017_P1_17095a_R_43_IGO_08944_B_3_S84_R1_001.fastq.gz\",\n"
            + "                \"/igo/delivery/FASTQ/PITT_0319_BH3MV7BBXY/Project_08944_B/Sample_LTG017_P1_17095a_R_43_IGO_08944_B_3/LTG017_P1_17095a_R_43_IGO_08944_B_3_S84_R2_001.fastq.gz\"\n"
            + "              ]\n"
            + "            }\n"
            + "          ]\n"
            + "        }\n"
            + "      ],\n"
            + "      \"cmoPatientId\": \"C-4LM16H\",\n"
            + "      \"metaDbPatientId\": \"52d04e35-64e5-42e7-84ef-7b6584adc541\",\n"
            + "      \"igoId\": \"08944_B_3\",\n"
            + "      \"investigatorSampleId\": \"LTG017_P1_17095a_R_43\",\n"
            + "      \"species\": \"Human\",\n"
            + "      \"sex\": \"M\",\n"
            + "      \"tumorOrNormal\": \"Tumor\",\n"
            + "      \"preservation\": \"Frozen\",\n"
            + "      \"specimenType\": \"PDX\",\n"
            + "      \"sampleOrigin\": \"Tissue\",\n"
            + "      \"tissueLocation\": \"\",\n"
            + "      \"baitSet\": \"IMPACT468_BAITS\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"metaDbSampleId\": \"05f04cc4-c53d-4674-a54d-29f95912f434\",\n"
            + "      \"importDate\": \"2021-03-18\",\n"
            + "      \"cmoSampleName\": \"C-4LM16H-N001-d\",\n"
            + "      \"sampleName\": \"17-0010557a\",\n"
            + "      \"cmoSampleClass\": \"Normal\",\n"
            + "      \"collectionYear\": \"\",\n"
            + "      \"tubeId\": \"\",\n"
            + "      \"qcReports\": [],\n"
            + "      \"libraries\": [\n"
            + "        {\n"
            + "          \"barcodeId\": \"IDT65\",\n"
            + "          \"barcodeIndex\": \"TGGAACAA\",\n"
            + "          \"libraryIgoId\": \"08944_B_4_1_1_1\",\n"
            + "          \"libraryVolume\": 35,\n"
            + "          \"libraryConcentrationNgul\": 34.1,\n"
            + "          \"dnaInputNg\": null,\n"
            + "          \"captureConcentrationNm\": \"4.9853372434017595\",\n"
            + "          \"captureInputNg\": \"170.0\",\n"
            + "          \"captureName\": \"Pool-08944_B-Tube7_1\",\n"
            + "          \"runs\": [\n"
            + "            {\n"
            + "              \"runMode\": \"HiSeq High Output\",\n"
            + "              \"runId\": \"PITT_0319\",\n"
            + "              \"flowCellId\": \"H3MV7BBXY\",\n"
            + "              \"readLength\": \"\",\n"
            + "              \"runDate\": \"2019-02-11\",\n"
            + "              \"flowCellLanes\": [\n"
            + "                5\n"
            + "              ],\n"
            + "              \"fastqs\": [\n"
            + "                \"/igo/delivery/FASTQ/PITT_0319_BH3MV7BBXY/Project_08944_B/Sample_17-0010557a_IGO_08944_B_4/17-0010557a_IGO_08944_B_4_S85_R1_001.fastq.gz\",\n"
            + "                \"/igo/delivery/FASTQ/PITT_0319_BH3MV7BBXY/Project_08944_B/Sample_17-0010557a_IGO_08944_B_4/17-0010557a_IGO_08944_B_4_S85_R2_001.fastq.gz\"\n"
            + "              ]\n"
            + "            }\n"
            + "          ]\n"
            + "        }\n"
            + "      ],\n"
            + "      \"cmoPatientId\": \"C-4LM16H\",\n"
            + "      \"metaDbPatientId\": \"52d04e35-64e5-42e7-84ef-7b6584adc541\",\n"
            + "      \"igoId\": \"08944_B_4\",\n"
            + "      \"investigatorSampleId\": \"17-0010557a\",\n"
            + "      \"species\": \"Human\",\n"
            + "      \"sex\": \"M\",\n"
            + "      \"tumorOrNormal\": \"Normal\",\n"
            + "      \"preservation\": \"Frozen\",\n"
            + "      \"specimenType\": \"Blood\",\n"
            + "      \"sampleOrigin\": \"Whole Blood\",\n"
            + "      \"tissueLocation\": \"\",\n"
            + "      \"baitSet\": \"IMPACT468_BAITS\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"metaDbSampleId\": \"1b3e23c7-7647-468d-aeed-08d0b02479e2\",\n"
            + "      \"importDate\": \"2021-03-18\",\n"
            + "      \"cmoSampleName\": \"C-MP76JR-N001-d\",\n"
            + "      \"sampleName\": \"17-0001535a\",\n"
            + "      \"cmoSampleClass\": \"Normal\",\n"
            + "      \"collectionYear\": \"\",\n"
            + "      \"tubeId\": \"\",\n"
            + "      \"qcReports\": [],\n"
            + "      \"libraries\": [\n"
            + "        {\n"
            + "          \"barcodeId\": \"IDT41\",\n"
            + "          \"barcodeIndex\": \"CGACTGGA\",\n"
            + "          \"libraryIgoId\": \"08944_B_2_1_1_1\",\n"
            + "          \"libraryVolume\": 35,\n"
            + "          \"libraryConcentrationNgul\": 33.5,\n"
            + "          \"dnaInputNg\": null,\n"
            + "          \"captureConcentrationNm\": \"5.074626865671642\",\n"
            + "          \"captureInputNg\": \"170.0\",\n"
            + "          \"captureName\": \"Pool-08944_B-Tube7_1\",\n"
            + "          \"runs\": [\n"
            + "            {\n"
            + "              \"runMode\": \"HiSeq High Output\",\n"
            + "              \"runId\": \"PITT_0319\",\n"
            + "              \"flowCellId\": \"H3MV7BBXY\",\n"
            + "              \"readLength\": \"\",\n"
            + "              \"runDate\": \"2019-02-11\",\n"
            + "              \"flowCellLanes\": [\n"
            + "                5\n"
            + "              ],\n"
            + "              \"fastqs\": [\n"
            + "                \"/igo/delivery/FASTQ/PITT_0319_BH3MV7BBXY/Project_08944_B/Sample_17-0001535a_IGO_08944_B_2/17-0001535a_IGO_08944_B_2_S83_R2_001.fastq.gz\",\n"
            + "                \"/igo/delivery/FASTQ/PITT_0319_BH3MV7BBXY/Project_08944_B/Sample_17-0001535a_IGO_08944_B_2/17-0001535a_IGO_08944_B_2_S83_R1_001.fastq.gz\"\n"
            + "              ]\n"
            + "            }\n"
            + "          ]\n"
            + "        }\n"
            + "      ],\n"
            + "      \"cmoPatientId\": \"C-MP76JR\",\n"
            + "      \"metaDbPatientId\": \"24d192a1-d4c6-4acf-8c2d-38acb231839a\",\n"
            + "      \"igoId\": \"08944_B_2\",\n"
            + "      \"investigatorSampleId\": \"17-0001535a\",\n"
            + "      \"species\": \"Human\",\n"
            + "      \"sex\": \"F\",\n"
            + "      \"tumorOrNormal\": \"Normal\",\n"
            + "      \"preservation\": \"Frozen\",\n"
            + "      \"specimenType\": \"Blood\",\n"
            + "      \"sampleOrigin\": \"Whole Blood\",\n"
            + "      \"tissueLocation\": \"\",\n"
            + "      \"baitSet\": \"IMPACT468_BAITS\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"metaDbSampleId\": \"4c067a73-8f83-4e4b-84d2-9206c6debca9\",\n"
            + "      \"importDate\": \"2021-03-18\",\n"
            + "      \"cmoSampleName\": \"C-MP76JR-X001-d\",\n"
            + "      \"sampleName\": \"LTG002_P3_17096_L1\",\n"
            + "      \"cmoSampleClass\": \"Primary\",\n"
            + "      \"oncoTreeCode\": \"SCLC\",\n"
            + "      \"collectionYear\": \"\",\n"
            + "      \"tubeId\": \"\",\n"
            + "      \"qcReports\": [],\n"
            + "      \"libraries\": [\n"
            + "        {\n"
            + "          \"barcodeId\": \"IDT29\",\n"
            + "          \"barcodeIndex\": \"ATTGAGGA\",\n"
            + "          \"libraryIgoId\": \"08944_B_1_1_1_1\",\n"
            + "          \"libraryVolume\": 35,\n"
            + "          \"libraryConcentrationNgul\": 34.8,\n"
            + "          \"dnaInputNg\": null,\n"
            + "          \"captureConcentrationNm\": \"11.49425287356322\",\n"
            + "          \"captureInputNg\": \"400.0\",\n"
            + "          \"captureName\": \"Pool-08944_B-Tube7_1\",\n"
            + "          \"runs\": [\n"
            + "            {\n"
            + "              \"runMode\": \"HiSeq High Output\",\n"
            + "              \"runId\": \"PITT_0319\",\n"
            + "              \"flowCellId\": \"H3MV7BBXY\",\n"
            + "              \"readLength\": \"\",\n"
            + "              \"runDate\": \"2019-02-11\",\n"
            + "              \"flowCellLanes\": [\n"
            + "                5\n"
            + "              ],\n"
            + "              \"fastqs\": [\n"
            + "                \"/igo/delivery/FASTQ/PITT_0319_BH3MV7BBXY/Project_08944_B/Sample_LTG002_P3_17096_L1_IGO_08944_B_1/LTG002_P3_17096_L1_IGO_08944_B_1_S82_R1_001.fastq.gz\",\n"
            + "                \"/igo/delivery/FASTQ/PITT_0319_BH3MV7BBXY/Project_08944_B/Sample_LTG002_P3_17096_L1_IGO_08944_B_1/LTG002_P3_17096_L1_IGO_08944_B_1_S82_R2_001.fastq.gz\"\n"
            + "              ]\n"
            + "            }\n"
            + "          ]\n"
            + "        }\n"
            + "      ],\n"
            + "      \"cmoPatientId\": \"C-MP76JR\",\n"
            + "      \"metaDbPatientId\": \"24d192a1-d4c6-4acf-8c2d-38acb231839a\",\n"
            + "      \"igoId\": \"08944_B_1\",\n"
            + "      \"investigatorSampleId\": \"LTG002_P3_17096_L1\",\n"
            + "      \"species\": \"Human\",\n"
            + "      \"sex\": \"F\",\n"
            + "      \"tumorOrNormal\": \"Tumor\",\n"
            + "      \"preservation\": \"Frozen\",\n"
            + "      \"specimenType\": \"PDX\",\n"
            + "      \"sampleOrigin\": \"Tissue\",\n"
            + "      \"tissueLocation\": \"\",\n"
            + "      \"baitSet\": \"IMPACT468_BAITS\"\n"
            + "    }\n"
            + "  ]\n"
            + "}";

    public static void main(String[] args) {
        SpringApplication.run(ConsistencyCheckerApp.class, args);
    }

    @Override
    public void run(String... args) throws Exception {
        if (util.isConsistent(referenceJson, targetJson)) {
            System.out.println("Both the jsons are the same");
        } else {
            System.out.println("Both the jsons are different");
        }
    }
    
}